server:
  port: 8085
spring:
  application:
    name: order
  data:
    mongodb:
      database: order
      username: admin
      password: admin
      port: 27017
      host: localhost
      authentication-database: admin
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

